type:
    - int8_t
    - uint8_t
    - int16_t
    - uint16_t
    - int32_t
    - uint32_t
    - int64_t
    - uint64_t
    - size_t
    - STRING
    - CodecID
    - AVPacketSideDataType
    - AVDiscard
    - AVStreamParseType
    - AVColorPrimaries
    - AVColorTransferCharacteristic
    - AVColorSpace
    - AVColorRange
    - AVChromaLocation
    - AVLPCType
    - AVAudioServiceType
    - AVSampleFormat
    - AVMediaType
    - PixelFormat
    - AVPictureType

define:
    - AV_DICT_IGNORE_SUFFIX
    - AVMEDIA_TYPE_VIDEO
    - AVMEDIA_TYPE_AUDIO
    - AVMEDIA_TYPE_SUBTITLE
    - AV_TIME_BASE
    - PIX_FMT_NONE
    - PIX_FMT_RGB24
    - PIX_FMT_YUV420P
    - SWS_BILINEAR
    - AV_LOG_QUIET
    # encode
    - CODEC_ID_MPEG2VIDEO
    - CODEC_ID_MPEG1VIDEO
    - CODEC_FLAG_GLOBAL_HEADER
    - CODEC_ID_NONE
    - AVFMT_GLOBALHEADER
    - CODEC_CAP_FRAME_THREADS
    - CODEC_CAP_SLICE_THREADS
    - CODEC_CAP_AUTO_THREADS

alias:
    - ByteIOContext
    - AVMetadata

class:
    - N8AVPacket4DOT_30E
    - N8AVStream4DOT_33E
    - AVProfile
    - AVPanScan
    - AVCodec
    - RcOverride
    - AVFrame
    - AVPaletteControl
    - AVHWAccel
    - AVCodecParser
    - AVFormatParameters
    - AVCodecContext
    - AVCodecParserContext
    - AVIndexEntry
    - AVDictionary
    - AVIOContext
    - AVOption
    - AVCodecTag
    - AVMetadataConv
    - AVProbeData
    - AVRational
    - AVFrac
    - AVClass
    - AVInputFormat
    - AVOutputFormat
    - AVStream
    - AVPacketList
    - AVStream
    - AVPacket
    - AVProgram
    - AVChapter
    - AVPacketList
    - AVFormatContext
    - AVPicture
    - SwsContext
    - SwsFilter
    - SwsVector
    # 0.8
    - AVCodecInternal
    - AVFieldOrder
    - AVCodecDefault
    - AVIOInterruptCB
    - AVDictionaryEntry


import:
    - from ctypes import CDLL, RTLD_GLOBAL
    - from ctypes import Structure, POINTER, CFUNCTYPE
    - from ctypes import c_int, c_uint, c_char, c_void_p, c_char_p, c_ubyte
    - from ctypes import c_short
    - from ctypes import c_ulong
    - from ctypes import c_int8, c_uint8
    - from ctypes import c_int16, c_uint16
    - from ctypes import c_int32, c_uint32
    - from ctypes import c_int64, c_uint64
    - from ctypes import c_float    
    - from ctypes import c_double
    - from ctypes import util

cdll:
    
    - libavutil = util.find_library('avutil')
    - CDLL(libavutil, RTLD_GLOBAL)
    - _libraries = {}
    - libavcodec = util.find_library('avcodec')
    - _libraries['libavcodec.so'] = CDLL(libavcodec, mode=RTLD_GLOBAL)
    - libavdevice = util.find_library('avdevice')
    - _libraries['libavdevice.so'] = CDLL(libavdevice, mode=RTLD_GLOBAL)
    - libavformat = util.find_library('avformat')
    - _libraries['libavformat.so'] = CDLL(libavformat, mode=RTLD_GLOBAL)
    - libswscale = util.find_library('swscale')
    - _libraries['libswscale.so'] = CDLL(libswscale, mode=RTLD_GLOBAL)
    
function:
    # TODO: sort by lib - avcodec, avformat...
    - av_register_all
    - avformat_open_input
    - avformat_find_stream_info
    - av_dict_get
    - av_oformat_next
    - avcodec_find_decoder
    - avcodec_find_decoder_by_name
    - avcodec_find_encoder_by_name
    - av_iformat_next
    - avcodec_get_pix_fmt_name
    - av_log_set_level
    - av_strerror
    - av_read_frame
    - avcodec_decode_audio4
    - av_samples_get_buffer_size
    - avcodec_decode_video2
    - av_find_stream_info
    - avcodec_open
    # sws
    - sws_getContext
    - avpicture_alloc
    - sws_scale
    - avcodec_alloc_frame
    # test
    - avpicture_get_size
    - avpicture_alloc
    - avpicture_fill
    - av_malloc
    - av_guess_format
    - avformat_alloc_context
    - av_dup_packet
    # encoding
    - avcodec_find_encoder
    - avformat_new_stream
    - av_get_sample_fmt_name
    - av_get_bytes_per_sample
